we-oauth2:
  additional:
    clientsDetails:
      - clientId: api-rent-app
        clientSecret: $2a$10$c3lyO4120V3X9TfVjSZDWuirXOzyLckfEcS1/loVYy3c/NLyuYBPi # rent-app-secret
        resourceIds:
          - vst-oauth2
          - vst-identity
          - vst-files
          - rent-app
        scope:
          - read
          - vst-client
        authorizedGrantTypes:
          - password
          - refresh_token
        registeredRedirectUri:
          - http://localhost/test
        authorities:
          - ROLE_TRUSTED_CLIENT
          - WE_IDENTITY_READ

      - clientId: rent-app
        clientSecret: $2a$10$pl4s4XGNDYZc1Dvh3eYVfuQPC.JyA3bcEfM3AHNyVDzB1ItykCX8. # rent-app-secret
        resourceIds:
          - vst-identity
          - vst-files
          - vst-oauth2
        scope:
          - read
        authorizedGrantTypes:
          - client_credentials
        authorities:
          - ROLE_TRUSTED_CLIENT
          - WE_IDENTITY_READ
          - WE_IDENTITY_WRITE
          - WE_PRIVACY_READ
          - WE_PRIVACY_WRITE
          - WE_OAUTH2_WRITE
          - WE_OAUTH2_READ
